"""
Compute event-level contributions to a global Pearson correlation.

For one selected feature x and target/prediction y:

    xz_i = (x_i - mean(x)) / std(x)
    yz_i = (y_i - mean(y)) / std(y)

    alignment_i = xz_i * yz_i
    contribution_i = alignment_i / N

Then:

    mean(alignment_i) = sum(contribution_i) = Pearson r

Interpretation:
    contribution_i > 0:
        event i supports a positive correlation because x and y are on the
        same side of their respective means.
    contribution_i < 0:
        event i supports a negative correlation because x and y are on
        opposite sides of their respective means.
    contribution_i near 0:
        at least one variable is close to its mean, so the event contributes
        little to the correlation.

The input is the per_event_importance.csv generated by
per_event_importance_fixed.py.
"""

from __future__ import annotations


# ===========================================================================
# READING GUIDE
# ===========================================================================
#
# Pearson correlation is normally one number calculated across all events.
# A mathematically valid "Pearson r for one event" does not exist because one
# event provides no distribution or variance.
#
# This file instead decomposes the GLOBAL Pearson r into additive event terms.
#
# For each event i:
#
#       x_z(i) = [x(i) - mean(x)] / std(x)
#       y_z(i) = [y(i) - mean(y)] / std(y)
#
#       alignment(i) = x_z(i) * y_z(i)
#       contribution(i) = alignment(i) / N
#
# The key identity checked by this program is:
#
#       sum_i contribution(i) = Pearson r
#
# Sign interpretation:
#
#   contribution > 0
#       x and y are both above their means, or both below their means.
#       The event pushes the overall relationship in the positive direction.
#
#   contribution < 0
#       one variable is above its mean while the other is below its mean.
#       The event pushes the overall relationship in the negative direction.
#
# Output figures:
#
#   1. COLZ-like two-dimensional histogram:
#        shows event density in feature-versus-target space.
#
#   2. Ranked event-contribution plot:
#        shows the individual events that most strongly push r positive or
#        negative.
#
# The color density is a count of events per bin. The Pearson contribution and
# Pearson r are dimensionless even when the target itself has physical units.
#
# ===========================================================================


import argparse
import os
import re

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


def safe_filename(value: str) -> str:
    """Convert a label into a Windows-safe filename component."""
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", value).strip("_")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot per-event contributions to a Pearson correlation."
    )
    parser.add_argument(
        "--input-csv",
        required=True,
        help="per_event_importance.csv generated by the per-event analysis.",
    )
    parser.add_argument(
        "--feature",
        required=True,
        help="Feature name without the z__ prefix, e.g. p_tot.",
    )
    parser.add_argument(
        "--target",
        required=True,
        help="Target name, e.g. Nu_Mom_X.",
    )
    parser.add_argument(
        "--target-source",
        choices=("predicted", "true"),
        default="predicted",
        help="Use pred__<target> or target__<target> as y.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=20,
        help="Number of strongest positive and negative events to show.",
    )
    parser.add_argument(
        "--bins",
        type=int,
        default=40,
        help="Number of bins per axis for the COLZ-like 2D histogram.",
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory for the CSV and PNG outputs.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if args.top_k <= 0:
        raise SystemExit("--top-k must be greater than zero.")
    if args.bins <= 1:
        raise SystemExit("--bins must be greater than one.")

    if not os.path.isfile(args.input_csv):
        raise SystemExit(f"Input CSV does not exist: {args.input_csv}")

    os.makedirs(args.output_dir, exist_ok=True)

    table = pd.read_csv(args.input_csv)

    x_column = f"z__{args.feature}"
    y_prefix = "pred" if args.target_source == "predicted" else "target"
    y_column = f"{y_prefix}__{args.target}"

    missing = [
        column
        for column in ("event", "csv_row", x_column, y_column)
        if column not in table.columns
    ]
    if missing:
        available_features = sorted(
            column.removeprefix("z__")
            for column in table.columns
            if column.startswith("z__")
        )
        available_targets = sorted(
            column.removeprefix(f"{y_prefix}__")
            for column in table.columns
            if column.startswith(f"{y_prefix}__")
        )
        raise SystemExit(
            f"Missing required columns: {missing}\n"
            f"Available features: {available_features}\n"
            f"Available {args.target_source} targets: {available_targets}"
        )

    x = pd.to_numeric(table[x_column], errors="coerce").to_numpy(np.float64)
    y = pd.to_numeric(table[y_column], errors="coerce").to_numpy(np.float64)

    finite = np.isfinite(x) & np.isfinite(y)
    if finite.sum() < 3:
        raise SystemExit(
            "Fewer than three finite feature/target pairs are available."
        )

    work = table.loc[finite, ["event", "csv_row"]].copy().reset_index(drop=True)
    x = x[finite]
    y = y[finite]

    x_mean = float(np.mean(x))
    y_mean = float(np.mean(y))
    x_std = float(np.std(x, ddof=0))
    y_std = float(np.std(y, ddof=0))

    if not np.isfinite(x_std) or x_std == 0:
        raise SystemExit(
            f"{x_column} has zero or invalid variation; Pearson r is undefined."
        )
    if not np.isfinite(y_std) or y_std == 0:
        raise SystemExit(
            f"{y_column} has zero or invalid variation; Pearson r is undefined."
        )

    # Step 1: center each variable around its split-level mean.
    x_centered = x - x_mean
    y_centered = y - y_mean

    # Step 2: convert both variables into split-level z-scores.
    #
    # This makes the calculation unitless, so GeV/c and normalized feature
    # values can be compared inside the Pearson formula.
    x_z = x_centered / x_std
    y_z = y_centered / y_std

    # Step 3: calculate the event's signed standardized alignment.
    #
    # Same-sign deviations give a positive value.
    # Opposite-sign deviations give a negative value.
    alignment = x_z * y_z

    # Step 4: divide by the number of events so the event terms add exactly
    # to the global Pearson coefficient.
    n_events = alignment.size
    contribution = alignment / n_events

    # Compute r in two independent ways:
    #   1. sum of the event-level contributions;
    #   2. NumPy's direct Pearson calculation.
    #
    # They must agree, otherwise the decomposition is wrong.
    pearson_from_terms = float(np.sum(contribution))
    pearson_direct = float(np.corrcoef(x, y)[0, 1])

    if not np.isclose(
        pearson_from_terms,
        pearson_direct,
        rtol=1.0e-10,
        atol=1.0e-12,
    ):
        raise RuntimeError(
            "Internal check failed: event contributions do not sum to Pearson r."
        )

    work["feature"] = args.feature
    work["target"] = args.target
    work["target_source"] = args.target_source
    work["x_value"] = x
    work["y_value"] = y
    work["x_minus_mean"] = x_centered
    work["y_minus_mean"] = y_centered
    work["x_z_within_split"] = x_z
    work["y_z_within_split"] = y_z
    work["event_alignment"] = alignment
    work["pearson_contribution"] = contribution
    work["absolute_contribution"] = np.abs(contribution)
    work["contribution_direction"] = np.where(
        contribution > 0,
        "supports positive r",
        np.where(contribution < 0, "supports negative r", "neutral"),
    )

    ranked = work.sort_values(
        "absolute_contribution", ascending=False
    ).reset_index(drop=True)
    ranked["absolute_rank"] = np.arange(1, len(ranked) + 1)

    stem = safe_filename(
        f"{args.feature}_vs_{args.target}_{args.target_source}"
    )

    csv_path = os.path.join(
        args.output_dir,
        f"per_event_pearson_contributions_{stem}.csv",
    )
    ranked.to_csv(csv_path, index=False)

    summary = pd.DataFrame(
        [
            {
                "feature": args.feature,
                "target": args.target,
                "target_source": args.target_source,
                "n_events": n_events,
                "feature_mean": x_mean,
                "feature_std": x_std,
                "target_mean": y_mean,
                "target_std": y_std,
                "pearson_r": pearson_from_terms,
                "sum_event_contributions": float(np.sum(contribution)),
                "mean_event_alignment": float(np.mean(alignment)),
                "positive_contribution_events": int((contribution > 0).sum()),
                "negative_contribution_events": int((contribution < 0).sum()),
            }
        ]
    )
    summary_path = os.path.join(args.output_dir, f"summary_{stem}.csv")
    summary.to_csv(summary_path, index=False)

    # ------------------------------------------------------------------
    # Plot 1: COLZ-like 2D histogram of x versus y. The mean lines show
    # the sign structure behind the Pearson contribution.
    # ------------------------------------------------------------------
    fig, ax = plt.subplots(figsize=(8.6, 6.2))
    # hist2d is the Matplotlib analogue of a ROOT COLZ-style density plot:
    # each rectangular bin is colored according to the number of events in it.
    hist = ax.hist2d(x, y, bins=args.bins)
    cb = fig.colorbar(hist[3], ax=ax)
    cb.set_label("events per bin")

    ax.axvline(x_mean, linestyle="--", linewidth=1.0, label="feature mean")
    ax.axhline(y_mean, linestyle=":", linewidth=1.0, label="target mean")

    # Overlay the strongest positive and negative contributors so the user can
    # see which individual events drive the correlation.
    top_pos = work.nlargest(min(args.top_k, len(work)), "pearson_contribution")
    top_neg = work.nsmallest(min(args.top_k, len(work)), "pearson_contribution")

    ax.scatter(
        top_pos["x_value"],
        top_pos["y_value"],
        s=26,
        marker="o",
        facecolors="none",
        linewidths=0.9,
        label="top positive contributors",
    )
    ax.scatter(
        top_neg["x_value"],
        top_neg["y_value"],
        s=26,
        marker="x",
        linewidths=0.9,
        label="top negative contributors",
    )

    ax.set_xlabel(f"{args.feature} (event-level normalized feature value)")
    ax.set_ylabel(f"{args.target} ({args.target_source})")
    ax.set_title(
        f"{args.feature} vs {args.target}: 2D density and event contributions\n"
        f"Pearson r = {pearson_from_terms:.4f}"
    )
    ax.grid(alpha=0.20)
    ax.legend(fontsize=8)
    fig.tight_layout()

    scatter_path = os.path.join(
        args.output_dir,
        f"hist2d_event_contributions_{stem}.png",
    )
    fig.savefig(scatter_path, dpi=300)
    plt.close(fig)

    # ------------------------------------------------------------------
    # Plot 2: strongest event contributions. All events remain in the CSV;
    # the figure shows only the most influential positive and negative ones.
    # ------------------------------------------------------------------
    positive_rows = (
        work[work["pearson_contribution"] > 0]
        .nlargest(args.top_k, "pearson_contribution")
    )
    negative_rows = (
        work[work["pearson_contribution"] < 0]
        .nsmallest(args.top_k, "pearson_contribution")
    )
    selected = pd.concat([negative_rows, positive_rows], ignore_index=True)
    selected = selected.sort_values("pearson_contribution")

    if not selected.empty:
        labels = [
            f"event {int(event)} (row {int(csv_row)})"
            for event, csv_row in zip(
                selected["event"],
                selected["csv_row"],
            )
        ]

        fig_height = max(5.0, 0.27 * len(selected) + 1.5)
        fig, ax = plt.subplots(figsize=(9.5, fig_height))

        negative_selected = selected["pearson_contribution"] < 0
        positive_selected = ~negative_selected

        positions = np.arange(len(selected))
        ax.barh(
            positions[negative_selected],
            selected.loc[
                negative_selected, "pearson_contribution"
            ],
            label="pushes r negative",
        )
        ax.barh(
            positions[positive_selected],
            selected.loc[
                positive_selected, "pearson_contribution"
            ],
            label="pushes r positive",
        )
        ax.set_yticks(positions)
        ax.set_yticklabels(labels, fontsize=7)
        ax.axvline(0.0, linewidth=0.8)
        ax.set_xlabel("additive event contribution to Pearson r")
        ax.set_title(
            f"Strongest event-level contributions\n"
            f"{args.feature} vs {args.target}; "
            f"all contributions sum to r = {pearson_from_terms:.4f}"
        )
        ax.grid(axis="x", alpha=0.25)
        ax.legend(fontsize=8)
        fig.tight_layout()

        top_path = os.path.join(
            args.output_dir,
            f"top_event_contributions_{stem}.png",
        )
        fig.savefig(top_path, dpi=300)
        plt.close(fig)
    else:
        top_path = None

    print("============================================================")
    print(f"Feature: {args.feature}")
    print(f"Target: {args.target} ({args.target_source})")
    print(f"Finite events: {n_events}")
    print(f"Pearson r: {pearson_from_terms:.8f}")
    print(
        "Check: sum(per-event Pearson contributions) = "
        f"{np.sum(contribution):.8f}"
    )
    print(
        "Check: mean(per-event standardized alignment) = "
        f"{np.mean(alignment):.8f}"
    )
    print(f"Wrote: {csv_path}")
    print(f"Wrote: {summary_path}")
    print(f"Wrote: {scatter_path}")
    if top_path:
        print(f"Wrote: {top_path}")
    print("============================================================")


if __name__ == "__main__":
    main()
